### ISSUE TITLE
Docker build did not work

### ISSUE THREAD

**Issue by heli80** [jboss-dockerfiles/jgroups#2]
Hi!
I would like to use this docker-image with a specific version (not 'latest') but the build for 3.6.10.Final on github is somehow broken: https://hub.docker.com/r/jboss/jgroups-gossip/builds/

Could you please have a look?
Thanks!
Heli

**Comment by ghost** [comment]
Something strange happened with docker hub, I've re-triggered the build

**Comment by heli80** [comment]
Thank you works like a charm now :-)
Br
