### ISSUE TITLE
docker rebuild for security fixes only works for 'latest'

### ISSUE THREAD

**Issue by heli80** [jboss-dockerfiles/jgroups#4]
Hi!
I'm depending on tag '3.6.10.Final' from the docker repo but unfortunately this tag was not rebuild even though a new jdk base image with security fixes was released.

BTW: The 'latest' tag was successfully updated - but i don't want to depend on 'latest'.

Thx in advance!
Heli

**Comment by ghost** [comment]
Apparently when the base repository changes, not all the tags are built by DockerHub (https://github.com/docker/hub-feedback/issues/518). Until figuring out how to workaround it, I just triggered a rebuild of the `3.6.10.Final` tag manually.
